name: Website

on:
  push:
    # For now, run on all commits to main
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  format-check:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Packages
        run: npm ci
        working-directory: website
      - name: Run Formatting Check
        run: npx prettier -c .
        working-directory: website
